/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reproductor.interfazGrafica.ventana;

import database.DBQuery;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import reproductor.Explorador;
import reproductor.ID3Tag;

/**
 *
 * @author usuario
 */
public class InterfazReproductor extends javax.swing.JFrame {

    /**
     * Creates new form InterfazReproductor
     */
    public InterfazReproductor(List<String[]> Informacion, List<String> Canciones, String directorio) {
        initComponents();
        this.informacion=Informacion;
        datos=new Object[Informacion.size()][4];
        this.canciones=Canciones;
        for(int i=0; i<Informacion.size(); i++){
            for(int j=0; j<4; j++){
                datos[i][j]=Informacion.get(i)[j];
            }
        }
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String [] {
                    "Title", "Artist", "Album", "Genero"
                })
        );
        jTable1.setAutoCreateRowSorter(true);
        ListSelectionModel model=jTable1.getSelectionModel();
        model.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(!model.isSelectionEmpty()){
                    int row=jTable1.getSelectedRow();
                    datoSeleccionado[0]=jTable1.getValueAt(row, 0).toString();
                    datoSeleccionado[1]=jTable1.getValueAt(row, 1).toString();
                    datoSeleccionado[2]=jTable1.getValueAt(row, 2).toString();
                    datoSeleccionado[3]=jTable1.getValueAt(row, 3).toString();
                }
                indiceObtenido=getIndex(datoSeleccionado);
                System.out.println(directorio+"\\"+canciones.get(indiceObtenido));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        play = new javax.swing.JLabel();
        stop = new javax.swing.JLabel();
        pause = new javax.swing.JLabel();
        selectFile = new javax.swing.JLabel();
        forward = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        display = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        songOption = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        albumOption = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        genderOption = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        artistOption = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        play.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductor/interfazGrafica/imagenes/play.png"))); // NOI18N
        play.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                playMouseReleased(evt);
            }
        });
        getContentPane().add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, -1, -1));

        stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductor/interfazGrafica/imagenes/stop.png"))); // NOI18N
        stop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                stopMouseReleased(evt);
            }
        });
        getContentPane().add(stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 590, -1, -1));

        pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductor/interfazGrafica/imagenes/pause.png"))); // NOI18N
        pause.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pauseMouseReleased(evt);
            }
        });
        getContentPane().add(pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, -1, -1));

        selectFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductor/interfazGrafica/imagenes/selectFile.png"))); // NOI18N
        selectFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                selectFileMouseReleased(evt);
            }
        });
        getContentPane().add(selectFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 590, -1, -1));

        forward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductor/interfazGrafica/imagenes/forward.png"))); // NOI18N
        getContentPane().add(forward, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 590, 60, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductor/interfazGrafica/imagenes/back.png"))); // NOI18N
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 590, 50, -1));

        display.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        display.setForeground(new java.awt.Color(255, 255, 255));
        display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 440, 20));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductor/interfazGrafica/imagenes/logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Euphemia", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AMusic");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Euphemia", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("The best way");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 790, 400));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        songOption.setOpaque(false);
        songOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                songOptionMousePressed(evt);
            }
        });
        songOption.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Song");
        songOption.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 15, -1, -1));

        jPanel1.add(songOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 290, 60));

        albumOption.setOpaque(false);
        albumOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                albumOptionMousePressed(evt);
            }
        });
        albumOption.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Album");
        albumOption.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 15, -1, -1));

        jPanel1.add(albumOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 290, 60));

        genderOption.setOpaque(false);
        genderOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                genderOptionMousePressed(evt);
            }
        });
        genderOption.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender");
        genderOption.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 15, -1, -1));

        jPanel1.add(genderOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 290, 60));

        artistOption.setOpaque(false);
        artistOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                artistOptionMousePressed(evt);
            }
        });
        artistOption.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Artist");
        artistOption.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 15, -1, -1));

        jPanel1.add(artistOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 290, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 530));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductor/interfazGrafica/imagenes/wallpaper.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopMouseReleased
        procesos.stop();
    }//GEN-LAST:event_stopMouseReleased

    private void playMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseReleased
        procesos.resume();
    }//GEN-LAST:event_playMouseReleased

    private void pauseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseMouseReleased
        procesos.pause();
    }//GEN-LAST:event_pauseMouseReleased

    private void selectFileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectFileMouseReleased
        Explorador ex=new Explorador();
        String directorio=ex.abrirExplorador();
        String directorioA=directorio;
        if(ex.getCanciones("")!=null){
            canciones=ex.getCanciones(directorio);
        }
        List <String[]> Informacion=new ArrayList<String[]>();
        for(String cancion:canciones){
            directorioA+="\\"+cancion;
            Informacion.add(ID3Tag.getID3TagList(directorioA));
            directorioA=directorio;
        }
        
        this.informacion=Informacion;
        datos=new Object[Informacion.size()][4];
        for(int i=0; i<Informacion.size(); i++){
            for(int j=0; j<4; j++){
                datos[i][j]=Informacion.get(i)[j];
            }
        }
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String [] {
                    "Title", "Artist", "Album", "Genero"
                })
        );
        jTable1.setAutoCreateRowSorter(true);
        
    }//GEN-LAST:event_selectFileMouseReleased

    private void songOptionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_songOptionMousePressed
        // TODO add your handling code here:
        setColor(songOption);
        resetColor(albumOption);
        resetColor(genderOption);
        resetColor(artistOption);
    }//GEN-LAST:event_songOptionMousePressed

    private void albumOptionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_albumOptionMousePressed
        // TODO add your handling code here:
        setColor(albumOption);
        resetColor(songOption);
        resetColor(genderOption);
        resetColor(artistOption);
    }//GEN-LAST:event_albumOptionMousePressed

    private void genderOptionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genderOptionMousePressed
        // TODO add your handling code here:
        setColor(genderOption);
        resetColor(songOption);
        resetColor(albumOption);
        resetColor(artistOption);
    }//GEN-LAST:event_genderOptionMousePressed

    private void artistOptionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_artistOptionMousePressed
        // TODO add your handling code here:
        setColor(artistOption);
        resetColor(songOption);
        resetColor(genderOption);
        resetColor(albumOption);
    }//GEN-LAST:event_artistOptionMousePressed
    
    
    private void setColor(JPanel panel){
        panel.setBackground(new Color(0, 0, 0));
        panel.setOpaque(true);
        
    }
    
    private void resetColor(JPanel panel){
        panel.setBackground(new Color(60,63,65));
        panel.setOpaque(false);
        
        System.out.println("oliii");
        
    }
    
    
    private int getIndex(String[] infoObtenida){
        for(String[] info:this.informacion){
            if(info[0]==infoObtenida[0]&&info[1]==infoObtenida[1]&&info[2]==infoObtenida[2]&&info[3]==infoObtenida[3]){
                return this.informacion.indexOf(info);
            }
        }
        return 1;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel albumOption;
    private javax.swing.JPanel artistOption;
    private javax.swing.JLabel back;
    private javax.swing.JLabel background;
    private javax.swing.JLabel display;
    private javax.swing.JLabel forward;
    private javax.swing.JPanel genderOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel pause;
    private javax.swing.JLabel play;
    private javax.swing.JLabel selectFile;
    private javax.swing.JPanel songOption;
    private javax.swing.JLabel stop;
    // End of variables declaration//GEN-END:variables
    private ProcesosReproduccion procesos = new ProcesosReproduccion();
    private Explorador exp;
    private String directorio;
    String[] datoSeleccionado=new String[4];
    private List<String[]> informacion;
    private int indiceObtenido;
    private List<String> canciones;
    private DBQuery query;
    private Object[][] datos;
}
