/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.interfazGrafica.ventana;

import database.DBQuery;
import formatos.Email;
import java.awt.Color;
<<<<<<< HEAD
import formatos.Password;
import java.awt.event.*;
=======
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
>>>>>>> cbc25b36e56bbc2185981078b535e48e2baaa8cb


/**
 *
 * @author usuario
 */
public class Sign_In extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Sign_In() {
        initComponents();
        this.setLocationRelativeTo(null);
<<<<<<< HEAD
        userPlaceHolder();
        passwordPlaceHolder();   
        emailPlaceHolder();
        con=new DBQuery();
=======
        
        /*userPlaceHolder();
        passwordPlaceHolder();   
        emailPlaceHolder();*/
>>>>>>> cbc25b36e56bbc2185981078b535e48e2baaa8cb
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        iconUser = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        signInButton = new javax.swing.JButton();
        emailField = new javax.swing.JTextField();
        fondoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitButton.setBackground(new java.awt.Color(0, 0, 0));
        exitButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.setBorderPainted(false);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 10, -1, -1));

        iconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/interfazGrafica/imagenes/logo_icon.png"))); // NOI18N
        getContentPane().add(iconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 180));

        userField.setBackground(new java.awt.Color(51, 51, 51));
        userField.setFont(new java.awt.Font("Euphemia", 1, 16)); // NOI18N
        userField.setForeground(new java.awt.Color(255, 255, 255));
        userField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldActionPerformed(evt);
            }
        });
        getContentPane().add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 250, 27));
        userField.getAccessibleContext().setAccessibleDescription("");

        passwordField.setBackground(new java.awt.Color(51, 51, 51));
        passwordField.setFont(new java.awt.Font("Euphemia", 0, 16)); // NOI18N
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 250, 27));

        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Do have account? Log In");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new MouseAdapter(){
                public void mouseClicked(MouseEvent evt){
                    jLabel3actionperformed(evt);
                    
                }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        signInButton.setBackground(new java.awt.Color(3, 3, 59));
        signInButton.setForeground(new java.awt.Color(255, 255, 255));
        signInButton.setText("Sign In");
<<<<<<< HEAD
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 170, -1));
=======
        getContentPane().add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 170, -1));
>>>>>>> cbc25b36e56bbc2185981078b535e48e2baaa8cb

        emailField.setBackground(new java.awt.Color(51, 51, 51));
        emailField.setFont(new java.awt.Font("Euphemia", 0, 16)); // NOI18N
        emailField.setForeground(new java.awt.Color(255, 255, 255));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 250, 27));

        fondoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/interfazGrafica/imagenes/wallpaper_login_3.jpg"))); // NOI18N
        getContentPane().add(fondoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldActionPerformed
        // TODO add your handling code her
        
    }//GEN-LAST:event_userFieldActionPerformed
<<<<<<< HEAD

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        // TODO add your handling code here:
        if(!Email.mailRegex(emailField.getText())){
            emailField.setText("");
            System.out.println("ingrese un email valido");
        }
        
        if(userField.getText().length()==0 || passwordField.getPassword().length==0 || emailField.getText().length()==0){
            System.out.println("Uno de los campos está vacio");
        }else{
            if(con.isInSignin(Password.chartoPass(passwordField.getPassword()), userField.getText())){
                con.ingresandoADB(userField.getText(), Password.chartoPass(passwordField.getPassword()), emailField.getText());
            }else{
                System.out.println("El nombre de usuario y contraseña ya se encuentran en la base de datos como un solo registro");
            }
        }
    }//GEN-LAST:event_signInButtonActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed
=======
    private void jLabel3actionperformed(MouseEvent evt){
        Log_In ventanaLogIn = new Log_In();
        ventanaLogIn.setVisible(true);
        Sign_In.this.dispose();
    }
>>>>>>> cbc25b36e56bbc2185981078b535e48e2baaa8cb
    private void userPlaceHolder(){
        userPlaceHolder = new com.placeholder.PlaceHolder(userField, "username");
        
        userPlaceHolder.setFont("Euphemia");
        userPlaceHolder.setColorHolder(Color.gray);
        userPlaceHolder.setSize(16);
    }
    private void passwordPlaceHolder(){
        passwordPlaceHolder = new com.placeholder.PlaceHolder(passwordField, "password");
        passwordPlaceHolder.setFont("Euphemia");
        passwordPlaceHolder.setColorHolder(Color.gray);
        passwordPlaceHolder.setSize(16);
    }
    private void emailPlaceHolder(){
        emailPlaceHolder = new com.placeholder.PlaceHolder(emailField, "E-mail");
        emailPlaceHolder.setFont("Euphemia");
        emailPlaceHolder.setColorHolder(Color.gray);
        emailPlaceHolder.setSize(16);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_In().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailField;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel fondoLabel;
    private javax.swing.JLabel iconUser;
    private javax.swing.JLabel jLabel3;
<<<<<<< HEAD
=======
    private javax.swing.JButton signInButton;
>>>>>>> cbc25b36e56bbc2185981078b535e48e2baaa8cb
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton signInButton;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
    private com.placeholder.PlaceHolder userPlaceHolder;
    private com.placeholder.PlaceHolder passwordPlaceHolder;
    private com.placeholder.PlaceHolder emailPlaceHolder;
    private DBQuery con;
}
